### PR TITLE
Add Sigrok/PulseView Dumps of HydraNFC Shield v2 (ST25R3916)

### PR DESCRIPTION
**Pull request by bvernoux**
…ST25R3916 NFC chipset communication using SPI + IRQ pin) for scan/read UID of NFC-A/B/V and read all ST25R3916 registers Space A & B

### CODE REVIEW

**Comment by bvernoux** [comment]
If you want also the decoder and all files including pvs see https://github.com/hydrabus/st25r3916_decoder_dumps_sigrok

**Comment by abraxa** [comment]
In ...Read_All_Registers_SpaceA_B.sr there are some packets where the PD emits the "excess byte" and "unknown register SpaceB" warnings. Is this expected and intentional?

**Comment by bvernoux** [comment]
I do not have such issue with PulseView Nightly from 11 July 2020 (on Windows 7)
Are you sure you have used Clock Polarity = 0 and Clock Phase = 1 ? (I suspect you do not have set those settings in ST25R3916 decoder as I can reproduce such errors when Clock Polarity=0 and Clock Phase=0)

**Comment by abraxa** [comment]
Merged in 944df7c1cd39a6b2319a5f20d5ffce74d3727619, thanks!

**Pull request closed without merging**
