### PR TITLE
avr_isp: add dump for ATmega328/P

### PR DESCRIPTION
**Pull request by rudis**

### CODE REVIEW

**Comment by fenugrec** [comment]
- [ ] signal labels - looks mostly good, should SCK and RST be renamed CLK and CS so they automatically matches the underlying SPI channel names ?
- [x] readme
- [x] test suite PR linked : https://github.com/sigrokproject/sigrok-test/pull/23
- [ ] I haven't personally tested yet

**Comment by rudis** [comment]
I looked at the other avr_isp tests and noticed they aren't consistent with the signal labels so I just copied them from one of the tests. Regarding, RST: It's not equivalent to CS (as it's also used to reset the device while flashing) so I think it should have a separate name.

**Comment by fenugrec** [comment]
Ok for RST != CS. For the clock, I see "SCK" is indeed the name given in the atmega328 datasheet so I believe this is fine.

**Comment by stefanct** [comment]
I have noticed varying usage of SCK vs. CLK in a number of tests concerning SPI as well. IMHO this should be homogenized eventually as it is just annoying and just a mistake. I'd use SCK because it is a bit more specific and very commonly used in SPI hardware but essentially I wouldn't care if it were CLK either. Just my 2¢.

**Comment by abraxa** [comment]
Merged as e2c49eb88327ac4eaaa41c160b9e3faa1d9ca1da, thank you!

**Pull request closed without merging**
